### ISSUE TITLE
Blurry Secondary Monitor Display

### ISSUE THREAD

**Issue by Utkarsh-Kumar384** [Speeedo83/Dell-Inspiron-5491-2in1-Hakintosh#1]
Firstly I'd like to thank you for putting together this EFI up online.
Now comes the issue. So, The issue that I'm facing is not exactly a major one but it for sure would be a Quality of Life change you can make to improvise it. 

So I was just going about putting the EFI folder on my drive and replacing AirportBrcm with Aiportlwm and Intel Bluetooth Injectors. Then once I booted it up and saw that the display isn't as crisp as it should be. There is a slight blur to anything that is displayed on the secondary monitor. I have set the resolution to 1080p as that's the max that my monitor supports but the issue still persists.

Secondly, I like to just confirm that if the Bluetooth microphone works? As that too doesn't seem to work with the EFI. 
Edit: Upon more fiddling, I found out that the monitor is actually zoomed at native 1080p resolution.
Thanks

**Comment by Speeedo83** [comment]
If you look at the description, the built-in microphone is not working, I bought a mini dongle to remedy the problem. Then describe your other problem regarding wifi and display

**Comment by Speeedo83** [comment]
in the afternoon today? I will insert new updated efi, with some improvements. For the BT microphone, the bug persists ... because it goes through the intel audio device ... and it is not compatible with mac .. sorry

**Comment by Utkarsh-Kumar384** [comment]
Well as for WIFI it's working, I got it working by removing AirportBrcmFixup and adding Airportlwm. 

However, as for the display it's rather zoomed in by a little bit even at its native resolution of 1080p. When I go fullscreen I can't see my top bar and exit full screen. Plus screen is pretty blurry(guessing it's because the display is zoomed).

**Comment by Utkarsh-Kumar384** [comment]
> 
> 
> in the afternoon today? I will insert new updated efi, with some improvements. For the BT microphone, the bug persists ... because it goes through the intel audio device ... and it is not compatible with mac .. sorry

Okay I'm waiting for it. Is there any way to contact you in like discord? If yes, then can you please add me Danzy#4588

**Comment by Speeedo83** [comment]
Sing it on
https://t.me/HackintoshLife_it

**Comment by Utkarsh-Kumar384** [comment]
Umm, I joined but was removed from the group.

**Comment by Speeedo83** [comment]
i up the new efi...test
And you enter in telegram group
Tnk
Can i help you,and i send you picture with four monitor connected any issue

**Comment by Speeedo83** [comment]
I update all

**Comment by Speeedo83** [comment]
In telegram group,set username and enter..

**Comment by Utkarsh-Kumar384** [comment]
Okay,  I tried the new one and the issue still persists. Any thing I can do?

Can I have your personal username for telegram? as I am getting removed time and again in the group
Thanks
